Paginação adicionada
indigotech/onboard-guilherme-khoury pull request #15
Opened 2021-09-20 00:21 UTC by guikhoury

<img width="934" alt="Screen Shot 2021-09-19 at 21 17 20" src="https://user-images.githubusercontent.com/44622971/133947740-20b09dd6-9ffb-41bd-bcb5-043c0d5fb9b4.png">

2021-09-20 12:50 UTC, alanraso requested changes

2021-09-20 12:50 UTC, alanraso commented on src/UsersList.tsx
> +    const offset = currentPage * dataPerPage;
Essas duas constantes poderiam ficar fora do componente tbm, no mesmo arquivo.

2021-09-20 12:50 UTC, alanraso commented on src/UsersList.tsx
> +    }
Aqui me parece que ele só faz a paginação até os usuários que retornam na primeira query. A ideia da paginação é vc ir pedindo mais usuários ao servidor, ou seja, fazer mais queries depenendo da página selecionada. Dá uma olhada no retorno completo da query users pra vc ver como funciona.

2021-09-20 18:25 UTC, Educ71 commented on src/UsersList.tsx
> +        return 'Erro! ${error.message}';
para adicionar um valor na string n da pra usar aspas `''`, tem que usar literal template  ` `` `

2021-09-21 19:26 UTC, guikhoury commented
<img width="568" alt="Screen Shot 2021-09-21 at 16 19 58" src="https://user-images.githubusercontent.com/44622971/134234900-57526225-28df-45cc-9c80-c2f8f2807d82.png">

2021-09-21 19:50 UTC, Educ71 commented on src/LoginScreen.tsx
> +  async function HandleSubmit(e: any) {
função a gente costuma usar camelCase, aqui seria `handleSubmit`

2021-09-21 19:53 UTC, Educ71 approved these changes

2021-09-21 20:31 UTC, alanraso approved these changes

2021-09-21 21:16 UTC, merged